# Generated by Django 4.0.4 on 2022-05-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0002_alter_resume_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_you',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hobbies',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pin',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skill',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
